### Importación de datos

In [2]:
import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda.head()

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Asistente virtual,Electrónicos,164300.0,6900.0,16/01/2021,Pedro Gomez,Bogotá,4,Tarjeta de crédito,8,4.60971,-74.08175
1,Mesa de comedor,Muebles,192300.0,8400.0,18/05/2022,Beatriz Morales,Medellín,1,Tarjeta de crédito,4,6.25184,-75.56359
2,Juego de mesa,Juguetes,209600.0,15900.0,15/03/2021,Juan Fernandez,Cartagena,1,Tarjeta de crédito,1,10.39972,-75.51444
3,Microondas,Electrodomésticos,757500.0,41000.0,03/05/2022,Juan Fernandez,Cali,4,Nequi,1,3.43722,-76.52250
4,Silla de oficina,Muebles,335200.0,20200.0,07/11/2020,Maria Alfonso,Medellín,5,Nequi,1,6.25184,-75.56359

#1. Análisis de facturación

In [3]:
df = pd.concat([tienda, tienda2, tienda3, tienda4], ignore_index=True)

df['Fecha de Compra'] = pd.to_datetime(df['Fecha de Compra'], dayfirst=True)

df['Facturacion'] = df['Precio'] + df['Costo de envío']

print("Facturación total: ", df['Facturacion'].sum())
print("Facturación promedio por compra: ", df['Facturacion'].mean())

facturacion_por_categoria = df.groupby('Categoría del Producto')['Facturacion'].sum().sort_values(ascending=False)
print("\nFacturación por categoría de producto:")
print(facturacion_por_categoria)

df['Mes'] = df['Fecha de Compra'].dt.to_period('M')
facturacion_por_mes = df.groupby('Mes')['Facturacion'].sum()
print("\nFacturación por mes:")
print(facturacion_por_mes)

top_productos = df.groupby('Producto')['Facturacion'].sum().sort_values(ascending=False).head(10)
print("\nTop 10 productos por facturación:")
print(top_productos)

Facturación total:  4638316200.0
Facturación promedio por compra:  491607.44038155803

Facturación por categoría de producto:
Categoría del Producto
Electrónicos               1.749039e+09
Electrodomésticos          1.395147e+09
Muebles                    7.981114e+08
Instrumentos musicales     3.672769e+08
Deportes y diversión       1.506693e+08
Juguetes                   7.762570e+07
Artículos para el hogar    6.069090e+07
Libros                     3.975600e+07
Name: Facturacion, dtype: float64

Facturación por mes:
Mes
2020-01    113055400.0
2020-02    113708800.0
2020-03    127030500.0
2020-04    143377600.0
2020-05    128661000.0
2020-06    101800400.0
2020-07    125539200.0
2020-08    117641200.0
2020-09    122419200.0
2020-10     95457500.0
2020-11    105914200.0
2020-12    118860200.0
2021-01    106339800.0
2021-02    117043000.0
2021-03    126299400.0
2021-04    126999100.0
2021-05    108024300.0
2021-06    108157100.0
2021-07    140049500.0
2021-08    134053200.0
2021-09    126818200.0
2021-10    121332600.0
2021-11    138637600.0
2021-12    146181700.0
2022-01    149576900.0
2022-02    113983000.0
2022-03    109529400.0
2022-04    111791200.0
2022-05    118763300.0
2022-06    101851000.0
2022-07    101633100.0
2022-08    117545800.0
2022-09    137183200.0
2022-10     97582100.0
2022-11    116200500.0
2022-12    122654100.0
2023-01    101507100.0
2023-02    114585900.0
2023-03    110528900.0
Freq: M, Name: Facturacion, dtype: float64

Top 10 productos por facturación:
Producto
TV LED UHD 4K       455524500.0
Iphone 15           422445600.0
Refrigerador        405393000.0
Smart TV            305662600.0
Lavadora de ropa    255357300.0
Lavavajillas        253345200.0
Tablet ABXY         230721200.0
Secadora de ropa    221432200.0
Celular ABXY        166322800.0
Batería             155680600.0
Name: Facturacion, dtype: float64

# 2. Ventas por categoría

In [4]:
ventas_por_categoria = df.groupby('Categoría del Producto').size().sort_values(ascending=False)
print("Cantidad de ventas por categoría:\n", ventas_por_categoria)

facturacion_por_categoria = df.groupby('Categoría del Producto')['Facturacion'].sum().sort_values(ascending=False)
print("\nFacturación por categoría:\n", facturacion_por_categoria)

Cantidad de ventas por categoría:
 Categoría del Producto
Muebles                    1886
Electrónicos               1772
Juguetes                   1290
Electrodomésticos          1149
Deportes y diversión       1113
Instrumentos musicales      753
Libros                      742
Artículos para el hogar     730
dtype: int64

Facturación por categoría:
 Categoría del Producto
Electrónicos               1.749039e+09
Electrodomésticos          1.395147e+09
Muebles                    7.981114e+08
Instrumentos musicales     3.672769e+08
Deportes y diversión       1.506693e+08
Juguetes                   7.762570e+07
Artículos para el hogar    6.069090e+07
Libros                     3.975600e+07
Name: Facturacion, dtype: float64

# 3. Calificación promedio de la tienda

In [5]:
tienda["Tienda"] = "Tienda 1"
tienda2["Tienda"] = "Tienda 2"
tienda3["Tienda"] = "Tienda 3"
tienda4["Tienda"] = "Tienda 4"

df = pd.concat([tienda, tienda2, tienda3, tienda4], ignore_index=True)

calificacion_promedio_tienda = df.groupby("Tienda")["Calificación"].mean()
print("Calificación promedio por tienda:\n", calificacion_promedio_tienda)

Calificación promedio por tienda:
 Tienda
Tienda 1    3.976685
Tienda 2    4.037304
Tienda 3    4.048326
Tienda 4    3.995759
Name: Calificación, dtype: float64

# 4. Productos más y menos vendidos

In [6]:
productos_vendidos = df['Producto'].value_counts()

print("Top 10 productos más vendidos:\n", productos_vendidos.head(10))
print("\nTop 10 productos menos vendidos:\n", productos_vendidos.tail(10))

Top 10 productos más vendidos:
 Producto
Mesa de noche                210
Carrito de control remoto    206
Microondas                   206
Batería                      203
Cama king                    201
Secadora de ropa             200
Modelado predictivo          200
Set de ollas                 200
Cama box                     199
Bloques de construcción      199
Name: count, dtype: int64

Top 10 productos menos vendidos:
 Producto
Olla de presión                172
Smartwatch                     172
Set de vasos                   169
Sillón                         168
Asistente virtual              167
Ciencia de datos con Python    166
Guitarra eléctrica             165
Mochila                        163
Auriculares con micrófono      158
Celular ABXY                   157
Name: count, dtype: int64

# 5. Envío promedio por tienda

In [7]:
envio_promedio_tienda = df.groupby("Tienda")["Costo de envío"].mean()
print("Envío promedio por tienda:\n", envio_promedio_tienda)

Envío promedio por tienda:
 Tienda
Tienda 1    26018.609580
Tienda 2    25216.235693
Tienda 3    24805.680373
Tienda 4    23459.457167
Name: Costo de envío, dtype: float64